<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/css/error.css">
    <title>404</title>
</head>
<body>
    <div class="error-container">
        <h1>404</h1>
        <h2>страница не найдена</h2>
        <a href="/globalFeed">вернуться к новостям</a>
        <img src="/images/cat.png" alt="sad cat">
    </div>
</body>
</html>